Repository mockyeah/mockyeah, pull requests merged in 2018-02, with the labels that each got.

#72 feat: support optional https
  examples/mockyeah-https.js
  examples/respond-and-verify-expectation-https.js
  index.js
  lib/prepareConfig.js
  package.json
  server/index.js
  test/TestHelper.js
  test/integration/HttpsTest.js
  yarn.lock
Labels: enhancement

#77 [upgrade] 25 - Upgrade eslint to latest version
  .eslintignore
  .eslintrc
  app/lib/CapturePlayer.js
  app/lib/CaptureRecorder.js
  app/lib/Logger.js
  app/lib/RouteResolver.js
  app/lib/routeHandler.js
  config.js
  index.js
  package.json
  tasks/lint.js
  test/dummy/index.js
  test/integration/CapturePlayTest.js
  test/integration/CaptureRecordAndPlayTest.js
  test/integration/ConfigTest.js
  test/integration/HttpsTest.js
  test/integration/ResponseContentTypeTest.js
  test/integration/ResponseHeadersTest.js
  test/integration/ResponseLatencyTest.js
  test/integration/ResponseStatusTest.js
  test/integration/ResponseValidationTest.js
  test/integration/RouteExpectationTest.js
  test/integration/RoutePatternTest.js
  test/integration/RouteRegisterTest.js
  test/integration/ServerTest.js
  yarn.lock
Labels: clean up

#76 feat: support partial body matches
  app/lib/RouteResolver.js
  test/integration/RoutePatternTest.js
Labels: enhancement

#91 docs(readme): add npm badge via shields.io
  README.md
Labels: documentation
