Repository mockyeah/mockyeah, pull requests merged in 2019-12, with the labels that each got.

#488 chore: add more gitignores
  .gitignore
Labels: chore

#489 docs: update gatsby & react versions
  packages/mockyeah-docs/package-lock.json
  packages/mockyeah-docs/package.json
Labels: documentation

#490 docs: update contributing nvm install version
  packages/mockyeah-docs/src/pages/Contributing.md
Labels: documentation

#491 feat(fetch): proxy by default, add noProxy option
  packages/mockyeah-fetch/src/index.ts
  packages/mockyeah-fetch/src/types.ts
  packages/mockyeah/app/index.js
  packages/mockyeah/app/lib/proxyRoute.js
Labels: enhancement

#493 feat(fetch): log instance name and on mocking
  packages/mockyeah-fetch/src/index.ts
  packages/mockyeah-fetch/src/types.ts
  packages/mockyeah/app/index.js
  packages/mockyeah/test/integration/ResponseValidationTest.js
Labels: enhancement

#486 docs: recipes and examples page: examples, deps, and tests links
  packages/mockyeah-docs/src/menus.js
  packages/mockyeah-docs/src/pages/Recipes-and-Examples.md
Labels: documentation

#492 build: lerna package.json postinstall and contributing docs
  .travis.yml
  package.json
  packages/mockyeah-docs/src/pages/Contributing.md
Labels: chore

#495 feat: allow empty response
  packages/mockyeah-fetch/src/index.ts
  packages/mockyeah/app/lib/helpers.js
  packages/mockyeah/test/integration/RecordFormatScriptFileTest.js
  packages/mockyeah/test/integration/RecordFormatScriptFunctionTest.js
  packages/mockyeah/test/integration/ResponseValidationTest.js
Labels: enhancement

#496 chore: address vulns by version bumping chokidar
  packages/mockyeah/package.json
  yarn.lock
Labels: chore

#497 chore: address vulns by version bumping chokidar
  packages/mockyeah/package-lock.json
  packages/mockyeah/package.json
Labels: chore

#494 test: more reliable
  packages/mockyeah/test/integration/ClosePromiseTest.js
  packages/mockyeah/test/integration/ConfigTest.js
  packages/mockyeah/test/integration/LazyStartTest.js
  packages/mockyeah/test/integration/ProxyRouteTest.js
  packages/mockyeah/test/integration/READMETest.js
  packages/mockyeah/test/integration/RecordFormatScriptFileTest.js
  packages/mockyeah/test/integration/RouteExpectationTest.js
  packages/mockyeah/test/integration/RouteProxyMethodTest.js
  packages/mockyeah/test/integration/RouteProxyNoHeadersTest.js
  packages/mockyeah/test/integration/RouteProxyTest.js
  packages/mockyeah/test/integration/RouteRegisterTest.js
  packages/mockyeah/test/integration/RouteResetTest.js
  packages/mockyeah/test/integration/StartedPromiseTest.js
  packages/mockyeah/test/integration/WatchTest.js
Labels: test

#498 fix: test packages no websocket
  packages/mockyeah-test-jest/index.js
  packages/mockyeah-test-mocha/index.js
Labels: bug

#499 refactor: fetch methods on class
  packages/mockyeah-fetch/src/Expectation.ts
  packages/mockyeah-fetch/src/index.ts
  packages/mockyeah-fetch/src/types.ts
Labels: refactor

#501 chore(fetch): remove js files before unit test
  packages/mockyeah-fetch/package.json
Labels: test

#502 fix(fetch): full meta original normal
  packages/mockyeah-fetch/src/__tests__/normalize.test.ts
  packages/mockyeah-fetch/src/normalize.ts
Labels: bug

#503 fix(fetch): body always empty string
  packages/mockyeah-fetch/src/index.ts
  packages/mockyeah-fetch/src/parseBody.ts
Labels: bug

#504 fix(fetch): expect params default object
  packages/mockyeah-fetch/src/Expectation.ts
Labels: bug

#505 test(fetch): add for parse query from url in object
  packages/mockyeah-fetch/src/__tests__/normalize.test.ts
Labels: test

#506 fix(fetch): optional fetch init & response options
  packages/mockyeah-fetch/src/__tests__/index.test.ts
  packages/mockyeah-fetch/src/index.ts
  packages/mockyeah-fetch/src/respond.ts
  packages/mockyeah-fetch/src/types.ts
Labels: bug

#507 test(fetch): no proxy in tests else infinite
  packages/mockyeah-fetch/src/__tests__/index.test.ts
Labels: test

#508 feat(fetch): match cookies
  packages/mockyeah-fetch/src/__tests__/index.test.ts
  packages/mockyeah-fetch/src/index.ts
  packages/mockyeah-fetch/src/isMockEqual.ts
  packages/mockyeah-fetch/src/normalize.ts
  packages/mockyeah-fetch/src/types.ts
Labels: enhancement
